"""create contracts table

Revision ID: 8c48d6949252
Revises: b2d9589d5303
Create Date: 2026-10-09 21:55:28.259722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c48d6949252'
down_revision: Union[str, None] = 'b2d9589d5303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contract_type', sa.String(length=50), server_default=sa.text("'OTHER'"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contract_type IN ('NDA', 'EMPLOYMENT', 'SERVICE_AGREEMENT', 'VENDOR_AGREEMENT', 'DATA_PROCESSING_AGREEMENT', 'PRIVACY_POLICY', 'OTHER')", name='ck_contracts_contract_type'),
    sa.CheckConstraint("status IN ('DRAFT', 'UPLOADED', 'PROCESSING', 'ANALYZED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED')", name='ck_contracts_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_created_by'), 'contracts', ['created_by'], unique=False)
    op.create_index(op.f('ix_contracts_organization_id'), 'contracts', ['organization_id'], unique=False)
    op.create_index('ix_contracts_organization_status', 'contracts', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contracts_organization_status', table_name='contracts')
    op.drop_index(op.f('ix_contracts_organization_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_created_by'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
