"""add processing jobs and clauses

Revision ID: 9be9ccdad342
Revises: d44ec4630871
Create Date: 2026-10-10 09:35:43.999109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be9ccdad342'
down_revision: Union[str, None] = 'd44ec4630871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_version_id', sa.UUID(), nullable=False),
    sa.Column('clause_index', sa.Integer(), nullable=False),
    sa.Column('clause_type', sa.String(length=60), server_default=sa.text("'OTHER'"), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), server_default=sa.text("'RULE_BASED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("clause_type IN ('CONFIDENTIALITY', 'TERMINATION', 'INDEMNITY', 'LIABILITY', 'PAYMENT', 'RENEWAL', 'DATA_PROTECTION', 'INTELLECTUAL_PROPERTY', 'DISPUTE_RESOLUTION', 'GOVERNING_LAW', 'OTHER')", name='ck_clauses_type'),
    sa.CheckConstraint('clause_index >= 0', name='ck_clauses_index'),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_clauses_confidence'),
    sa.CheckConstraint('page_end IS NULL OR page_end >= 1', name='ck_clauses_page_end'),
    sa.CheckConstraint('page_start IS NULL OR page_end IS NULL OR page_end >= page_start', name='ck_clauses_page_range'),
    sa.CheckConstraint('page_start IS NULL OR page_start >= 1', name='ck_clauses_page_start'),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_version_id', 'clause_index', name='uq_clauses_version_index')
    )
    op.create_index(op.f('ix_clauses_contract_version_id'), 'clauses', ['contract_version_id'], unique=False)
    op.create_index('ix_clauses_version_type', 'clauses', ['contract_version_id', 'clause_type'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_version_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('TEXT_EXTRACTION', 'CLAUSE_EXTRACTION', 'FULL_ANALYSIS', 'REANALYSIS')", name='ck_processing_jobs_job_type'),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name='ck_processing_jobs_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_processing_jobs_attempt_count'),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name='ck_processing_jobs_completion_time'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_processing_jobs_max_attempts'),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_contract_version_id'), 'processing_jobs', ['contract_version_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_requested_by'), 'processing_jobs', ['requested_by'], unique=False)
    op.create_index('ix_processing_jobs_status_created', 'processing_jobs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processing_jobs_status_created', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_requested_by'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_contract_version_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_clauses_version_type', table_name='clauses')
    op.drop_index(op.f('ix_clauses_contract_version_id'), table_name='clauses')
    op.drop_table('clauses')
    # ### end Alembic commands ###
