"""add document chunks and embeddings

Revision ID: a2057bc66460
Revises: 9be9ccdad342
Create Date: 2026-10-10 14:09:01.377255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2057bc66460'
down_revision: Union[str, None] = '9be9ccdad342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='ck_document_chunks_chunk_index'),
    sa.CheckConstraint('page_end IS NULL OR page_end >= 1', name='ck_document_chunks_page_end'),
    sa.CheckConstraint('page_start IS NULL OR page_end IS NULL OR page_end >= page_start', name='ck_document_chunks_page_range'),
    sa.CheckConstraint('page_start IS NULL OR page_start >= 1', name='ck_document_chunks_page_start'),
    sa.CheckConstraint('token_count IS NULL OR token_count >= 0', name='ck_document_chunks_token_count'),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_version_id', 'chunk_index', name='uq_document_chunks_version_index')
    )
    op.create_index(op.f('ix_document_chunks_contract_version_id'), 'document_chunks', ['contract_version_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_chunks_contract_version_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
