"""create users table

Revision ID: b2d9589d5303
Revises: 06b400971fe0
Create Date: 2026-10-09 18:09:16.094417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d9589d5303'
down_revision: Union[str, None] = '06b400971fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=40), server_default=sa.text("'EMPLOYEE'"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'INVITED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('SUPER_ADMIN', 'ORG_ADMIN', 'LEGAL_REVIEWER', 'COMPLIANCE_OFFICER', 'EMPLOYEE')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INVITED', 'SUSPENDED', 'DEACTIVATED')", name='ck_users_status'),
    sa.CheckConstraint('email = lower(btrim(email))', name='ck_users_email_normalized'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
