"""add contract versions and documents

Revision ID: d44ec4630871
Revises: 8c48d6949252
Create Date: 2026-10-09 22:19:01.426780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44ec4630871'
down_revision: Union[str, None] = '8c48d6949252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version_number >= 1', name='ck_contract_versions_version_number'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'version_number', name='uq_contract_versions_contract_version')
    )
    op.create_index(op.f('ix_contract_versions_contract_id'), 'contract_versions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_versions_uploaded_by'), 'contract_versions', ['uploaded_by'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_version_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), server_default=sa.text("'s3'"), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'SCANNING', 'AVAILABLE', 'QUARANTINED', 'FAILED', 'DELETED')", name='ck_documents_status'),
    sa.CheckConstraint('file_size_bytes > 0', name='ck_documents_file_size_positive'),
    sa.CheckConstraint('sha256_checksum IS NULL OR length(sha256_checksum) = 64', name='ck_documents_sha256_length'),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key', name='uq_documents_storage_key')
    )
    op.create_index(op.f('ix_documents_contract_version_id'), 'documents', ['contract_version_id'], unique=False)
    op.create_index('ix_documents_version_status', 'documents', ['contract_version_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_version_status', table_name='documents')
    op.drop_index(op.f('ix_documents_contract_version_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_contract_versions_uploaded_by'), table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_contract_id'), table_name='contract_versions')
    op.drop_table('contract_versions')
    # ### end Alembic commands ###
